spring:
      datasource:
               url: jdbc:mysql://127.0.0.1:3306/outreach
               username: amit
               password: amit1986
               driver-class-name: com.mysql.jdbc.Driver
                            
      secondDatasource:  
               url: jdbc:mysql://127.0.0.1:3306/alexis
               username: amit
               password: amit1986
               driver-class-name: com.mysql.jdbc.Driver

server: 
       contextPath: /
       port: 9090
       
       

